name:                dwarf-play
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/k-bx/dwarf-play#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           Kostiantyn Rybnikov <k-bx@k-bx.com>
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  dwarf-play:
    source-dirs:      src
    main:             Main.hs
    ghc-options:      -rtsopts -g
